<div class="assigner-instructions">
    <h3><?php echo $this->__('Instructions'); ?></h3>
    <p>
        <?php echo $this->__('This module changes the option value of a selected attribute for multiple products at a time.'); ?>
        <br />
        <?php echo $this->__('It is dedicated (and limited) to "select" frontend_type attributes to fix a common mistake on case or mispellings during imports or updates.'); ?>
    </p>
    <h4><?php echo $this->__('Steps'); ?></h4>
    <ol>
        <li><?php echo $this->__('First select the attribute you wish to modify an option of.'); ?></li>
        <li>
            <?php echo $this->__('You will then be prompted to select (simple) products from a grid.'); ?>
            <br />
            <?php echo $this->__('The grid will show you the value for selected attribute for every simple product in your catalog.'); ?>
        </li>
        <li>
            <?php echo $this->__('Lastly, select the new value you wish to assign to that attribute for selected products.'); ?>
        </li>
        <li>
            <?php echo $this->__('A summary of your selections and the job to be done will then be displayed for you to validate.'); ?>
        </li>
    </ol>
    <p class="cheers">
        <?php echo $this->__('I hope this will be as useful for you as it has been for me and my customers.'); ?>
        <br />
        <?php echo $this->__('Cheers, bouni.'); ?>
    </p>        
</div>