<?php 
$helper = Mage::helper('bewai_attributeassigner');
$products = $helper->getSelectedValue('products');
?>

<?php if ($helper->getCurrentStep() == 'attribute') : ?>
    <?php echo $this->getChildHtml('instructions'); ?>
<?php endif; ?>

<?php if ($helper->getCurrentStep() == 'products') : ?>
    <?php $grid = $this->getChild('products-grid'); ?>
    <?php echo $grid->toHtml(); ?>
    <div class="submit-products">
        <button class="scalable" id="submitMassaction" title="Valider" type="button" style="">
            <span><span><span><?php echo $this->__('Submit'); ?></span></span></span>
        </button>
    </div>
    <script>
    $('submitMassaction').observe('click', function(e){
        Event.stop(e);
        <?php echo $grid->getMassactionBlock()->getJsObjectName(); ?>.apply();
    });
    
    <?php if ($products) : ?>
    <?php echo $grid->getMassactionBlock()->getJsObjectName(); ?>.checkedString = '<?php echo join(',', $products); ?>';
    <?php echo $grid->getMassactionBlock()->getJsObjectName(); ?>.checkCheckboxes();
    <?php endif; ?>
    </script>
<?php endif; ?>
    
<?php if ($helper->isReady()) : ?>
    <?php echo $this->getChildHtml('summary'); ?>
<?php endif; ?>
